<?php
$helper = Mage::helper('fballiano_turnstile');
if (!$helper->isEnabled()) return;
?><script>
    //TODO: load turnstile script only on demand
    let turnstileRenderedElements = [];
    function fballiano_turnstile_render(element) {
        console.log("ciao");
        if (turnstileRenderedElements.includes(element.id)) return;
        turnstileRenderedElements.push(element.id);
        turnstile.render(element, {sitekey: '<?= $helper->getSiteKey() ?>'});
    }
    document.addEventListener("DOMContentLoaded", function () {
        document.querySelectorAll('<?= $helper->getFrontendSelectors() ?>').forEach(function (element) {
            element.addEventListener('focusin', function (event) {
                fballiano_turnstile_render(element);
            });
        });
    });
</script>
<script src="https://challenges.cloudflare.com/turnstile/v0/api.js" defer></script>